### ISSUE TITLE
Error: Cannot find module '../../assets/data/output.json'

### ISSUE THREAD

**Issue by tlightsky** [phodal/phodit#12]
OS X 里yarn start遇到个问题

```
App threw an error during load
Error: Cannot find module '../../assets/data/output.json'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/Users/chaowang/source/js/phodit/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/Users/chaowang/source/js/phodit/dist/native/main.js:18:22)
    at Object.<anonymous> (/Users/chaowang/source/js/phodit/dist/native/main.js:339:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```

**Comment by phodal** [comment]
see in https://github.com/phodal/phodit/issues/2
