### ISSUE TITLE
Mac安装后如何启动？

### ISSUE THREAD

**Issue by lxw0109** [phodal/phodit#4]

**Comment by lxw0109** [comment]
请问Mac下如何安装，按照readme安装后如何启动编辑器？

**Comment by phodal** [comment]
```
yarn start
```

如果只是为了使用，可以从 release 标签下下载

**Comment by suhanyujie** [comment]
你好~，
使用 `yarn start`会遇到一些问题：

```
/www/2019/frontEnd/phodit(branch:master) » yarn start                                                                     suhanyu@suhanyudeMacBook-Pro
yarn run v1.7.0
$ yarn build:native && electron ./dist/native/main.js
$ tsc && cp -a views dist
App threw an error during load
Error: Cannot find module '../../assets/data/output.json'
    at Module._resolveFilename (internal/modules/cjs/loader.js:584:15)
    at Function.Module._resolveFilename (/www/2019/frontEnd/phodit/node_modules/electron/dist/Electron.app/Contents/Resources/electron.asar/common/reset-search-paths.js:43:12)
    at Function.Module._load (internal/modules/cjs/loader.js:510:25)
    at Module.require (internal/modules/cjs/loader.js:640:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/www/2019/frontEnd/phodit/dist/native/main.js:18:22)
    at Object.<anonymous> (/www/2019/frontEnd/phodit/dist/native/main.js:339:3)
    at Module._compile (internal/modules/cjs/loader.js:693:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:704:10)
    at Module.load (internal/modules/cjs/loader.js:602:32)
```

* 此时，我按照readme中所说，使用`./node_modules/.bin/electron-rebuild -p -t "dev,prod,optional"`，会错误如下：

```
/www/2019/frontEnd/phodit(branch:master) » ./node_modules/.bin/electron-rebuild -p -t "dev,prod,optional"                 suhanyu@suhanyudeMacBook-Pro
✖ Rebuild Failed

An unhandled error occurred inside electron-rebuild
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:610:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/www/2019/frontEnd/phodit/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=4.0.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /www/2019/frontEnd/phodit/node_modules/nodejieba
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1

Error: gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.0 | darwin | x64
gyp ERR! configure error
gyp ERR! stack Error: Command failed: /anaconda3/bin/python -c import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack   File "<string>", line 1
gyp ERR! stack     import sys; print "%s.%s.%s" % sys.version_info[:3];
gyp ERR! stack                                ^
gyp ERR! stack SyntaxError: invalid syntax
gyp ERR! stack
gyp ERR! stack     at ChildProcess.exithandler (child_process.js:294:12)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at maybeClose (internal/child_process.js:962:16)
gyp ERR! stack     at Socket.stream.socket.on (internal/child_process.js:381:11)
gyp ERR! stack     at Socket.emit (events.js:182:13)
gyp ERR! stack     at Pipe._handle.close (net.js:610:12)
gyp ERR! System Darwin 15.5.0
gyp ERR! command "/usr/local/bin/node" "/www/2019/frontEnd/phodit/node_modules/electron-rebuild/node_modules/.bin/node-gyp" "rebuild" "--target=4.0.2" "--arch=x64" "--dist-url=https://atom.io/download/electron" "--build-from-source"
gyp ERR! cwd /www/2019/frontEnd/phodit/node_modules/nodejieba
gyp ERR! node -v v10.15.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok

Failed with exit code: 1
    at SafeSubscriber._error (/www/2019/frontEnd/phodit/node_modules/spawn-rx/lib/src/index.js:277:84)
    at SafeSubscriber.__tryOrUnsub (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.error (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:201:26)
    at Subscriber._error (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:132:26)
    at Subscriber.error (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:106:18)
    at MapSubscriber.Subscriber._error (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:132:26)
    at MapSubscriber.Subscriber.error (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:106:18)
    at SafeSubscriber._next (/www/2019/frontEnd/phodit/node_modules/spawn-rx/lib/src/index.js:251:65)
    at SafeSubscriber.__tryOrUnsub (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:242:16)
    at SafeSubscriber.next (/www/2019/frontEnd/phodit/node_modules/rxjs/Subscriber.js:189:22)
```

**Comment by phodal** [comment]
@suhanyujie 需要创建 ``assets/data/output.json`` 这个文件，在里面创建一个空的对象数组 ``[{}]``，里面原来存放的是我的博客数据。

**Comment by phodal** [comment]
rebuild 的那个问题，看上去是 Python 版本的问题。

**Comment by suhanyujie** [comment]
额，从release里下载了一个，是可以运行的。
